version: '3'
services:
  library-client:
    image: "library-client:latest"
    ports:
     - "8080:80"
    depends_on:
     - library-backend    
  library-backend:
    image: "library-service:latest"
    ports:
     - "3500:3500"
    environment:
     - "MONGO_HOST=192.168.1.5"
     - "MONGO_PORT=27017"     
    depends_on:
     - mongo
    volumes:
     - ~/Desktop/testdata:/dist/testdata 
  mongo:
    image: "mongo:latest"
    ports: 
       - "27017:27017"
    volumes:
       - ~/mongodata:/data/db
  nginx-reverse:
    build: .
    image: "nginix-reverse:latest"
    # ports:
    #   - "12000:13000"
    network_mode: "host"
       